### ISSUE TITLE
bug::화상채팅 접속 시 nullpointer 에러 발생

### ISSUE THREAD

**Issue by SeJonJ** [SeJonJ/ChatForYou#29]
화상 채팅 접속 시 서버와의 연결 불안정, 세션 - kurentoendpoint 코드 이상의 이유로 nullpointer 에러 발생
- 이 외에도 exception 에 대한 코드 처리가 필요함

아래는 로그의 일부
```java
2023-11-07 11:36:47.830 ERROR 1 --- [nio-8443-exec-6] w.s.h.ExceptionWebSocketHandlerDecorator : Closing session due to exception for StandardWebSocketSession[id=04f800f2-ec6d-dd05-ff08-46acfa8e4f54, uri=wss://hjproject.kro.kr:8653/signal]
java.lang.IllegalStateException: The WebSocket session [0] has been closed and no method (apart from close()) may be called on a closed session
 at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:1082) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:639) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at webChat.rtc.KurentoUserSession.sendMessage(KurentoUserSession.java:318) ~[classes!/:na]
 at webChat.dto.KurentoRoomDto.joinRoom(KurentoRoomDto.java:199) ~[classes!/:na]
 at webChat.dto.KurentoRoomDto.join(KurentoRoomDto.java:147) ~[classes!/:na]
 at webChat.rtc.KurentoHandler.joinRoom(KurentoHandler.java:111) ~[classes!/:na]
 at webChat.rtc.KurentoHandler.handleTextMessage(KurentoHandler.java:59) ~[classes!/:na]
 at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) ~[spring-websocket-5.3.22.jar!/:5.3.22]
 at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
 at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.65.jar!/:na]
 at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by kimregular** [comment]
어쩌라고 바보야

**Comment by SeJonJ** [comment]
원인 : 화상 채팅 접속 후 서버와 통신 시 connection 에러로 인한 nullpointer, socket exception 등 발생
수정 : 각종 exception 발생 시 예외처리 및 서버에 에러시 front 에서 재접속 할 수 있도록 modal 출력

코드 반영 후 1주 동안 로그 확인 후 에러 없을 시 해당 이슈 close 예정

**Comment by SeJonJ** [comment]
23.11.11 기준 해당 에러는 더 이상 확인 불가
이슈 close
